# Generated by Django 3.2.8 on 2022-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarazData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=600)),
                ('url', models.CharField(max_length=500)),
                ('sku', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=10000)),
            ],
        ),
    ]
